TDT\SiteBundle\Entity\Mail:
    type: entity
    table: mails
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 32
        email:
            type: string
            scale: 60
        message:
            type: text


