parameters:
#    tdt_site.example.class: TDT\SiteBundle\Example

services:
    # Menu selected items
    tdt_site.menu.voter.request:
        class: TDT\SiteBundle\Menu\RequestVoter
        arguments:
            - @service_container
        tags:
            - { name: knp_menu.voter }
