parameters:
#    smart_gallery.example.class: SmartCore\Bundle\GalleryBundle\Example

services:
#    smart_gallery.example:
#        class: %smart_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
